version:  2
services:
    redis:
        image: redis
        networks:
            - back-end
    db:
        image: postgres:9.4
        networks:
            - back-end
    vote: 
        image: voiting-app
        networks:
            - back-end
            - front-end
    result:
        image: result
        networks:
            - back-end
            - front-end
networks:
    front-end:
    back-end:
